# 需要注意的是，所有的修改，都填在引号里面
application:
  name: '每日天气预报'
  mail:
    host: 'smtp.qq.com' #也可以改成其他的，比如qq邮箱
    port: '465' #也可以改成其他的，比如163邮箱
    username: '2592532554@qq.com' #username
    password: 'agmlofutqfxjdjah' #password
    default-encoding: 'utf-8'
  weather:
    appid: '46492968' #在www.tianqiapi.com申请的appid，有免费 api
    appsecret: '84ZE7HHB' #在www.tianqiapi.com申请的appsecret
girlfriend:
  mails:
    - '522022000027@smail.nju.edu.cn' # 女票的邮箱，可以写多个
#    - 'licongying4133@163.com' # 女票的邮箱，可以写多个
  city: '南京' #你女票所在的城市
  start_love_date: "2023-01-10" #开始在一起的日期，格式"2020-05-15"，请保持一致
  girlname: '聪崽' #对你的女票的爱称
  boyname: '好哥哥' #你在你女票那里的称呼